### ISSUE TITLE
我想问下conf.conf.properties中nginx.path 的配置问题

### ISSUE THREAD

**Issue by yuenwah** [onlyGuo/nginx-gui#10]
1）yum安装的nginx 我这里应该写什么，nginx 执行文件是在/usr/sbin/下面
2）我这页面显示正常，但只要有交互的操作就会报错日志如图
![image](https://user-images.githubusercontent.com/34834139/56797216-ce522480-6846-11e9-8693-dc2c05d4c639.png)
3）点这个按钮没任何反应，也没日志，在浏览器调试模式也没任何显示，感觉这里没这个按钮一样（chrome）
![image](https://user-images.githubusercontent.com/34834139/56797282-f477c480-6846-11e9-8a22-b2ae74d0f036.png)

**Comment by climba03003** [comment]
看見你使用 YUM 管理軟件
所以假設你是使 CentOS 系統
預設 設定檔應為
```
nginx.path = /usr/sbin/nginx
nginx.config = /etc/nginx/nginx.conf
account.admin = admin
```

**Comment by onlyGuo** [comment]
正解

**Comment by onlyGuo** [comment]
另外, 如果你的系统中, 配置了nginx的全局变量的话, 那么nginx.path这个参数也可以直接写"/", 如果问题解决请反馈一下哈~
