### ISSUE TITLE
无法添加规则

### ISSUE THREAD

**Issue by zhijianfree** [onlyGuo/nginx-gui#11]
无法添加规则
![image](https://user-images.githubusercontent.com/21210211/60077492-a440b400-975c-11e9-93a6-acc5737a6b96.png)

**Comment by zhijianfree** [comment]
新加规则的时候传入的是null就会报错

**Comment by onlyGuo** [comment]
嗯, 是的, 抽时间会修复, 最近忙...

**Comment by onlyGuo** [comment]
> 新加规则的时候传入的是null就会报错

已修复, 拉取新的代码并编译即可. 稍后我会打包一下.
