### ISSUE TITLE
默认用户名密码错误

### ISSUE THREAD

**Issue by zhongjiarun** [onlyGuo/nginx-gui#2]
大神，为什么部署好了使用默认管理员账号和密码会显示用户名和密码错误，可以给个配置文件的语法吗？
感激不尽！

**Comment by onlyGuo** [comment]
修改conf.properties, 这个文件默认在项目跟中, 如果无法读到配置文件, 请将他复制到上一层目录.
用户配置写法: 比如创建一个account = zhangsan, password = abc的用户, 写法如下:
account.zhangsan = abc

**Comment by onlyGuo** [comment]
如果编译为Jar包的话, 需要将conf.properties放到Jar包所在目录(非Jar包内)
