### ISSUE TITLE
为什么一直提示密码错误

### ISSUE THREAD

**Issue by yuenwah** [onlyGuo/nginx-gui#3]
为什么一直提示密码错误

**Comment by onlyGuo** [comment]
修改conf.properties, 这个文件默认在项目跟中, 如果无法读到配置文件, 请将他复制到上一层目录.
如果编译为Jar包的话, 需要将conf.properties放到Jar包所在目录(非Jar包内)

**Comment by onlyGuo** [comment]
先关闭, 如果问题未解决再打开这个Issues
