### ISSUE TITLE
nginx配置文件保存并热加载后，无法正确读取配置

### ISSUE THREAD

**Issue by threebo** [onlyGuo/nginx-gui#34]
![image](https://user-images.githubusercontent.com/111231786/184542463-4426de56-6e17-4d81-80a9-197ab761be4d.png)
![image](https://user-images.githubusercontent.com/111231786/184542523-1ca82053-8fba-4be8-96b4-b169e01bf603.png)

**Comment by onlyGuo** [comment]
现在在忙其他的事情，后期所有的问题会在2.0中一次性解决。
