### ISSUE TITLE
推荐一个部署方法

### ISSUE THREAD

**Issue by Lengff** [onlyGuo/nginx-gui#4]
如果不是java 程序员的话
1. jdk 1.8 并且配置环境变量 (自行百度)
2. 安装 maven 并且配置环境变量 (自行百度)
3. 修改 conf.properties 配置文件 像我是windows 下的路径为 D:/software/nginx-1.15.5/conf/nginx.conf
4. 在nginx-gui 目录 执行 `mvn spring-boot:run` 命令就可以了
如果是java程序员请 给我指出批评和不足

最后我希望作者有时间可以再弄弄,我发现很多的bug

**Comment by zhejiez** [comment]
问个问题,用户名密码admin不对啊

**Comment by onlyGuo** [comment]
第一个版本的发行包已经编译, 在GitHub中下载你对应的系统的发行包.
包内集成了Java运行环境, 无需手动配置JDK.
1. 下载好后, 解压, 修改conf/conf. properties文件, 将你的Nginx安装地址和Nginx配置文件地址设置进去.
2. 在配置文件中, `account.admin = admin `表示 创建一个admin的账户, 他的密码是admin, 若想添加一个用户为abc, 密码为123的用于, 在conf/conf. properties中追加一行 `account.abc = 123` 即可.
3. 设置好配置文件后, 运行startup.sh或startup.bat即可启动.
4. 访问端口8889

如有问题, 请重开lssues.
