### ISSUE TITLE
windows系统下路径带有空格的问题处理

### ISSUE THREAD

**Issue by wzshuang** [onlyGuo/nginx-gui#7]
如果nginx的安装目录包含空格，运行时可能会抛异常，在不改变代码的情况下可以按如下配置
`nginx.path = D:/Program Files/nginx-1.14.0`
`nginx.config = "D:/Program Files/nginx-1.14.0/conf/nginx.conf"`
也就是nginx.path正常填写，nginx.config加双引号这样就可以了。

**Comment by wzshuang** [comment]
我错了，按上面的配置，其他地方会报错。。
nginx.path包含空格不影响
nginx.config如果包含空格，要么改源码，要么单独把配置文件放在一个不包含空格的路径。

**Comment by onlyGuo** [comment]
好滴, 最近时间太忙了, 有时间修复下.

**Comment by climba03003** [comment]
設定內空白問題應該可以用 反斜 來解決吧

**Comment by onlyGuo** [comment]
近期抽时间解决

**Comment by onlyGuo** [comment]
该问题的修复版本已提交, lssues先关闭, 若问题依旧, 请重开lssues就好.
