### ISSUE TITLE
部分页面无法显示

### ISSUE THREAD

**Issue by tanganyu1114** [onlyGuo/nginx-gui#8]
---------------------------------
错误图片和文字
![image](https://user-images.githubusercontent.com/48984491/55065658-37fbd900-50b7-11e9-8caf-7932ff7cf610.png)
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Mar 27 17:23:19 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available

--------------------------------------
不知道是自己打包哪里出错了，还是哪里的需求不对，求作者帮忙解答一下，谢谢！
JDK版本：1.8.0_131
MVN版本：3.3.9

**Comment by onlyGuo** [comment]
是因为这个页面还没写出来 :)
